### ISSUE TITLE
Installation failed: Invalid bioc repo: 3.5/release/treeio

### ISSUE THREAD

**Issue by Angel-Popa** [guerreror/pepo#1]
Hi,  

I was getting the following error when Installing the package. 
`
library(devtools) 
install_github("guerreror/pepo") 
Downloading GitHub repo guerreror/pepo@master 
from URL https://api.github.com/repos/guerreror/pepo/zipball/master 
Installing pepo 
Installation failed: Invalid bioc repo: 3.5/release/treeio
`

I don't know if this might solve the problem long term, but I forked the packages and I modified the description by adding the package `treeio` into the list to be imported. After this modification, the installation was successful, independently of the BioC version I was running (3.5 to 3.7). 

Would this modification have some detrimental effect?

**Comment by guerreror** [comment]
Hi Angel, 
Sorry I didn't see this issue in so long. You're right. The inclusion of `treeio` as `remote` from Bioconductor was causing the problem. `treeio` isn't even a dependency, and I don't remember why I added it as a remote. I've moved it to `suggest` and included the `BiocViews:` line to the DESCRIPTION, which should do the trick.
Let me know if it worked for you, and if the package was helpful at all.
